---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: 9.11.1-alpine

inputs:
  - name: service-repo

outputs:
  - name: test-output

run:
  path: sh
  args: [ "./service-repo/ci/tasks/smoke-test/task.sh" ]
