---
resources:
- name: service-repo
  type: git
  source:
    uri: {{git-url}}
    branch: {{git-branch}}
    username: ((git-username))
    # please uncomment as applicable
#    password: ((git-passwd))
#    private_key: ((git-private-key))

- name: deploy-dev
  type: cf
  source:
    api:             {{pws-api}}
    username:        ((deploy-username))
    password:        ((deploy-password))
    skip_cert_check: true
    organization:    {{pws-organization}}
    space:           {{pws-space}}

jobs:
- name: build
  public: true
  serial: true
  plan:
  - get: service-repo
    trigger: true
  - task: create-archive
    privileged: true
    file: service-repo/ci/tasks/build-service/task.yml
  - put: deploy-dev
    params:
      manifest: build-output/manifest.yml
      path: build-output/*.jar

- name: smoke-test
  serial: true
  plan:
  - get: service-repo
    trigger: true
    passed: [ build-service ]
  - task: smoke-test-dev
    privileged: true
    file: service-repo/ci/tasks/smoke-test/task.yml
